apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-job
spec:
  taskManager:
    resource:
      memory: "3072m"
      cpu: 1.0
  job:
    args: [
      "--s3Bucket=promoted-event-logs",
      "--jobLabel=blue",
      "--sideOutputDebugLogging",
      "--startFromEarliest",
      # User property "is_host" - Hipcamp
      "--nonBuyerUserSparseHash=6102540093495235004",
      # User property "is_staff" - Hipcamp
      "--nonBuyerUserSparseHash=4078401918190321518",

      "--parallelism=2",
      "--maxParallelism=2",

      # Example flags to enable content joins.
      # "--contentApiRootUrl=http://ee1a-67-168-60-51.ngrok.io/",
      # "--contentApiKey=xyz",
      # "--contentApiSecretName=example-prod-content",
      # "--region=us-east-1",
      # Fields from the fake data generator.
      # "--contentIdFieldKeys=itemId",
      # "--contentIdFieldKeys=storeId",
      # "--contentIdFieldKeys=promotionId",

      # Periodically update the watermark locally.
      # Needs a longer delay for slow job startup.
      # Align the watermark since we have different input sources.
      "--watermarkAlignment",
      "--watermarkIdleness=PT1M",
      "--checkpointInterval=PT1M",
      # Dan - 2023-05-29-09 - Seeing if this helps.
      # "--defaultValidatedEventOutOfOrder=PT15M",

      # Keep the out of order times small to reduce resources in dev.
      "--flatResponseInsertionGapDuration=PT1M",
      "--combineDeliveryLogWindow=PT5S",
      "--insertionImpressionJoinMaxOutOfOrder=PT20S",
      "--impressionActionJoinMaxOutOfOrder=PT20S",
      "--no-disableAutoGeneratedUIDs",
      "--databaseName=flat_db",
      "--sideDatabaseName=flat_db_side",

      # Paimon settings
      "--writePaimonTables",
      "--partitionByHour=true",
      "--paimonBasePath=s3a://promoted-event-logs/paimon-test",
      "--paimonGlobalOptions=file.format=orc",
      "--paimonGlobalOptions=bucket=1",
      "--paimonGlobalOptions=sink.parallelism=1",
      "--paimonGlobalOptions=orc.write.batch-size=16",
    ]
  flinkConfiguration:
    taskmanager.memory.managed.fraction: "0.2"
    state.savepoints.dir: s3a://promoted-event-logs/flat-output-flink-job-blue/savepoints
    state.checkpoints.dir: s3a://promoted-event-logs/flat-output-flink-job-blue/checkpoints
    high-availability.storageDir: s3a://promoted-event-logs/flat-output-flink-job-blue/ha
