package ai.promoted.metrics.logprocessor.job.validateenrich;

import ai.promoted.metrics.logprocessor.common.job.testing.BaseJobUnitTest;
import java.time.Duration;

/** Unit tests (non-minicluster tests). */
public class ValidateEnrichJobUnitTest extends BaseJobUnitTest<ValidateEnrichJob> {
  @Override
  protected ValidateEnrichJob createJob() {
    ValidateEnrichJob job = new ValidateEnrichJob();
    job.checkpointInterval = Duration.ofSeconds(1);
    job.checkpointTimeout = Duration.ofSeconds(60);
    job.disableAutoGeneratedUIDs = false;
    job.configureExecutionEnvironment(env, 1, 0);
    env.getCheckpointConfig().enableUnalignedCheckpoints(false);
    return job;
  }
}
