apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../_base/_flink-job
namePrefix: sql-runner-
patches:
  - patch: |-
      - op: replace
        path: /spec/job/jarURI
        value: local:///opt/SqlRunnerJob_deploy.jar
    target:
      kind: FlinkDeployment
      name: flink-job
