package ai.promoted.metrics.logprocessor.common.functions;

import ai.promoted.proto.common.ClientInfo;
import ai.promoted.proto.common.Timing;
import ai.promoted.proto.common.UserInfo;
import ai.promoted.proto.delivery.Insertion;
import ai.promoted.proto.delivery.Request;
import ai.promoted.proto.event.Action;
import ai.promoted.proto.event.Impression;
import ai.promoted.proto.event.LogRequest;
import ai.promoted.proto.event.Session;
import ai.promoted.proto.event.SessionProfile;
import ai.promoted.proto.event.User;
import ai.promoted.proto.event.View;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class PushDownBatchFieldsTest {

  private static final long PLATFORM_ID = 1L;
  private static final String USER_ID = "userId1";
  private static final String CAMEL_CASED_LOG_USER_ID = "logUserId1";
  private static final String LOG_USER_ID = "loguserid1";
  private static final long TIME_EPOCH_MILLIS = 1601516627000L;

  private static final long OTHER_PLATFORM_ID = PLATFORM_ID + 1;
  private static final String OTHER_USER_ID = USER_ID + "alt";
  private static final String OTHER_LOG_USER_ID = LOG_USER_ID + "alt";
  private static final long OTHER_TIME_EPOCH_MILLIS = TIME_EPOCH_MILLIS + 1;

  private static final String SESSION_ID = "sessionId1";
  private static final String VIEW_ID = "viewId1";
  private static final String REQUEST_ID = "requestId1";
  private static final String INSERTION_ID = "insertionId1";
  private static final String IMPRESSION_ID = "impressionId1";
  private static final String ACTION_ID = "actionId1";
  private static final String SURFACE_NAME = "search";

  private static final ClientInfo CLIENT_INFO = ClientInfo.newBuilder()
          .setTrafficType(ClientInfo.TrafficType.PRODUCTION)
          .setClientType(ClientInfo.ClientType.PLATFORM_SERVER)
          .build();

  private Timing createTiming(long timestamp) {
    return Timing.newBuilder()
            .setClientLogTimestamp(timestamp)
            .build();
  }

  @Test
  public void pushDownAllFieldsTest() throws Exception {
    assertEquals(
        LogRequest.newBuilder()
            .setPlatformId(PLATFORM_ID)
            .setUserInfo(UserInfo.newBuilder()
                    .setUserId(USER_ID)
                    .setLogUserId(LOG_USER_ID))
            .setTiming(createTiming(TIME_EPOCH_MILLIS))
            .setClientInfo(CLIENT_INFO)
            .addUser(User.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder()
                            .setUserId(USER_ID)
                            .setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .setClientInfo(CLIENT_INFO))
            .addSessionProfile(SessionProfile.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder().setUserId(USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .setClientInfo(CLIENT_INFO)
                    .setSessionId(SESSION_ID))
            .addSession(Session.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .setClientInfo(CLIENT_INFO)
                    .setSessionId(SESSION_ID))
            .addView(View.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .setClientInfo(CLIENT_INFO)
                    .setViewId(VIEW_ID)
                    .setSessionId(SESSION_ID))
            .addRequest(Request.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .setClientInfo(CLIENT_INFO)
                    .setRequestId(REQUEST_ID)
                    .setViewId(VIEW_ID))
            .addInsertion(Insertion.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .setClientInfo(CLIENT_INFO)
                    .setInsertionId(INSERTION_ID)
                    .setRequestId(REQUEST_ID))
            .addImpression(Impression.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .setClientInfo(CLIENT_INFO)
                    .setInsertionId(INSERTION_ID)
                    .setImpressionId(IMPRESSION_ID))
            .addAction(Action.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .setClientInfo(CLIENT_INFO)
                    .setImpressionId(IMPRESSION_ID)
                    .setActionId(ACTION_ID))
            .build(),
        new PushDownBatchFields().map(
                LogRequest.newBuilder()
                        .setPlatformId(PLATFORM_ID)
                        .setUserInfo(UserInfo.newBuilder()
                                .setUserId(USER_ID)
                                .setLogUserId(LOG_USER_ID))
                        .setTiming(createTiming(TIME_EPOCH_MILLIS))
                        .setClientInfo(CLIENT_INFO)
                        .addUser(User.newBuilder())
                        .addSession(Session.newBuilder()
                                .setSessionId(SESSION_ID))
                        .addSessionProfile(SessionProfile.newBuilder()
                                .setSessionId(SESSION_ID))
                        .addView(View.newBuilder()
                                .setViewId(VIEW_ID)
                                .setSessionId(SESSION_ID))
                        .addRequest(Request.newBuilder()
                                .setRequestId(REQUEST_ID)
                                .setViewId(VIEW_ID))
                        .addInsertion(Insertion.newBuilder()
                                .setInsertionId(INSERTION_ID)
                                .setRequestId(REQUEST_ID))
                        .addImpression(Impression.newBuilder()
                                .setInsertionId(INSERTION_ID)
                                .setImpressionId(IMPRESSION_ID))
                        .addAction(Action.newBuilder()
                                .setImpressionId(IMPRESSION_ID)
                                .setActionId(ACTION_ID))
                        .build()));
  }

  @Test
  public void noPushDownSameFieldsTest() throws Exception {
    assertEquals(
            LogRequest.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder()
                            .setUserId(USER_ID)
                            .setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .addUser(User.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder()
                                    .setUserId(USER_ID)
                                    .setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS)))
                    .addSessionProfile(SessionProfile.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setUserId(USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setSessionId(SESSION_ID))
                    .addSession(Session.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setSessionId(SESSION_ID))
                    .addView(View.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setViewId(VIEW_ID)
                            .setSessionId(SESSION_ID))
                    .addRequest(Request.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setRequestId(REQUEST_ID)
                            .setViewId(VIEW_ID))
                    .addInsertion(Insertion.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setInsertionId(INSERTION_ID)
                            .setRequestId(REQUEST_ID))
                    .addImpression(Impression.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setInsertionId(INSERTION_ID)
                            .setImpressionId(IMPRESSION_ID))
                    .addAction(Action.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setImpressionId(IMPRESSION_ID)
                            .setActionId(ACTION_ID))
                    .build(),
            new PushDownBatchFields().map(
                    LogRequest.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder()
                                    .setUserId(USER_ID)
                                    .setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .addUser(User.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder()
                                            .setUserId(USER_ID)
                                            .setLogUserId(LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS)))
                            .addSessionProfile(SessionProfile.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setUserId(USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setSessionId(SESSION_ID))
                            .addSession(Session.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setSessionId(SESSION_ID))
                            .addView(View.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setViewId(VIEW_ID)
                                    .setSessionId(SESSION_ID))
                            .addRequest(Request.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setRequestId(REQUEST_ID)
                                    .setViewId(VIEW_ID))
                            .addInsertion(Insertion.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setInsertionId(INSERTION_ID)
                                    .setRequestId(REQUEST_ID))
                            .addImpression(Impression.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setInsertionId(INSERTION_ID)
                                    .setImpressionId(IMPRESSION_ID))
                            .addAction(Action.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setImpressionId(IMPRESSION_ID)
                                    .setActionId(ACTION_ID))
                            .build()));
  }

  @Test
  public void noPushDownDifferentFieldsTest() throws Exception {
    assertEquals(
            LogRequest.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder()
                            .setUserId(USER_ID)
                            .setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .addUser(User.newBuilder()
                            .setPlatformId(OTHER_PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder()
                                    .setUserId(OTHER_USER_ID)
                                    .setLogUserId(OTHER_LOG_USER_ID))
                            .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS)))
                    .addSessionProfile(SessionProfile.newBuilder()
                            .setPlatformId(OTHER_PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setUserId(OTHER_USER_ID))
                            .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                            .setSessionId(SESSION_ID))
                    .addSession(Session.newBuilder()
                            .setPlatformId(OTHER_PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                            .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                            .setSessionId(SESSION_ID))
                    .addView(View.newBuilder()
                            .setPlatformId(OTHER_PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                            .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                            .setViewId(VIEW_ID)
                            .setSessionId(SESSION_ID))
                    .addRequest(Request.newBuilder()
                            .setPlatformId(OTHER_PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                            .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                            .setRequestId(REQUEST_ID)
                            .setViewId(VIEW_ID))
                    .addInsertion(Insertion.newBuilder()
                              .setPlatformId(OTHER_PLATFORM_ID)
                              .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                              .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                              .setInsertionId(INSERTION_ID)
                              .setRequestId(REQUEST_ID))
                    .addImpression(Impression.newBuilder()
                              .setPlatformId(OTHER_PLATFORM_ID)
                              .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                              .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                              .setInsertionId(INSERTION_ID)
                              .setImpressionId(IMPRESSION_ID))
                    .addAction(Action.newBuilder()
                              .setPlatformId(OTHER_PLATFORM_ID)
                              .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                              .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                              .setImpressionId(IMPRESSION_ID)
                              .setActionId(ACTION_ID))
                    .build(),
            new PushDownBatchFields().map(
                    LogRequest.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder()
                                    .setUserId(USER_ID)
                                    .setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .addUser(User.newBuilder()
                                    .setPlatformId(OTHER_PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder()
                                            .setUserId(OTHER_USER_ID)
                                            .setLogUserId(OTHER_LOG_USER_ID))
                                    .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS)))
                            .addSessionProfile(SessionProfile.newBuilder()
                                    .setPlatformId(OTHER_PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setUserId(OTHER_USER_ID))
                                    .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                                    .setSessionId(SESSION_ID))
                            .addSession(Session.newBuilder()
                                    .setPlatformId(OTHER_PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                                    .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                                    .setSessionId(SESSION_ID))
                            .addView(View.newBuilder()
                                    .setPlatformId(OTHER_PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                                    .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                                    .setViewId(VIEW_ID)
                                    .setSessionId(SESSION_ID))
                            .addRequest(Request.newBuilder()
                                    .setPlatformId(OTHER_PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                                    .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                                    .setRequestId(REQUEST_ID)
                                    .setViewId(VIEW_ID))
                            .addInsertion(Insertion.newBuilder()
                                    .setPlatformId(OTHER_PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                                    .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                                    .setInsertionId(INSERTION_ID)
                                    .setRequestId(REQUEST_ID))
                            .addImpression(Impression.newBuilder()
                                    .setPlatformId(OTHER_PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                                    .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                                    .setInsertionId(INSERTION_ID)
                                    .setImpressionId(IMPRESSION_ID))
                            .addAction(Action.newBuilder()
                                    .setPlatformId(OTHER_PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(OTHER_LOG_USER_ID))
                                    .setTiming(createTiming(OTHER_TIME_EPOCH_MILLIS))
                                    .setImpressionId(IMPRESSION_ID)
                                    .setActionId(ACTION_ID))
                            .build()));
  }

  @Test
  public void lowerCaseLogUserId() throws Exception {
    assertEquals(
            LogRequest.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setUserInfo(UserInfo.newBuilder()
                            .setUserId(USER_ID)
                            .setLogUserId(LOG_USER_ID))
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .addUser(User.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder()
                                    .setUserId(USER_ID)
                                    .setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS)))
                    .addSessionProfile(SessionProfile.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setUserId(USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setSessionId(SESSION_ID))
                    .addSession(Session.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setSessionId(SESSION_ID))
                    .addView(View.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setViewId(VIEW_ID)
                            .setSessionId(SESSION_ID))
                    .addRequest(Request.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setRequestId(REQUEST_ID)
                            .setViewId(VIEW_ID))
                    .addInsertion(Insertion.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setInsertionId(INSERTION_ID)
                            .setRequestId(REQUEST_ID))
                    .addImpression(Impression.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setInsertionId(INSERTION_ID)
                            .setImpressionId(IMPRESSION_ID))
                    .addAction(Action.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setImpressionId(IMPRESSION_ID)
                            .setActionId(ACTION_ID))
                    .build(),
            new PushDownBatchFields().map(
                    LogRequest.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder()
                                    .setUserId(USER_ID)
                                    .setLogUserId(CAMEL_CASED_LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .addUser(User.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder()
                                            .setUserId(USER_ID)
                                            .setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS)))
                            .addSessionProfile(SessionProfile.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setUserId(USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setSessionId(SESSION_ID))
                            .addSession(Session.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setSessionId(SESSION_ID))
                            .addView(View.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setViewId(VIEW_ID)
                                    .setSessionId(SESSION_ID))
                            .addRequest(Request.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setRequestId(REQUEST_ID)
                                    .setViewId(VIEW_ID))
                            .addInsertion(Insertion.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setInsertionId(INSERTION_ID)
                                    .setRequestId(REQUEST_ID))
                            .addImpression(Impression.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setInsertionId(INSERTION_ID)
                                    .setImpressionId(IMPRESSION_ID))
                            .addAction(Action.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setImpressionId(IMPRESSION_ID)
                                    .setActionId(ACTION_ID))
                            .build()));
  }

  @Test
  public void ifNoTopLevelUserInfo() throws Exception {
    assertEquals(
            LogRequest.newBuilder()
                    .setPlatformId(PLATFORM_ID)
                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                    .addUser(User.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder()
                                    .setUserId(USER_ID)
                                    .setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS)))
                    .addSessionProfile(SessionProfile.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setUserId(USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setSessionId(SESSION_ID))
                    .addSession(Session.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setSessionId(SESSION_ID))
                    .addView(View.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setViewId(VIEW_ID)
                            .setSessionId(SESSION_ID))
                    .addRequest(Request.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setRequestId(REQUEST_ID)
                            .setViewId(VIEW_ID))
                    .addInsertion(Insertion.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setInsertionId(INSERTION_ID)
                            .setRequestId(REQUEST_ID))
                    .addImpression(Impression.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setInsertionId(INSERTION_ID)
                            .setImpressionId(IMPRESSION_ID))
                    .addAction(Action.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setUserInfo(UserInfo.newBuilder().setLogUserId(LOG_USER_ID))
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .setImpressionId(IMPRESSION_ID)
                            .setActionId(ACTION_ID))
                    .build(),
            new PushDownBatchFields().map(
                    LogRequest.newBuilder()
                            .setPlatformId(PLATFORM_ID)
                            .setTiming(createTiming(TIME_EPOCH_MILLIS))
                            .addUser(User.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder()
                                            .setUserId(USER_ID)
                                            .setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS)))
                            .addSessionProfile(SessionProfile.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setUserId(USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setSessionId(SESSION_ID))
                            .addSession(Session.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setSessionId(SESSION_ID))
                            .addView(View.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setViewId(VIEW_ID)
                                    .setSessionId(SESSION_ID))
                            .addRequest(Request.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setRequestId(REQUEST_ID)
                                    .setViewId(VIEW_ID))
                            .addInsertion(Insertion.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setInsertionId(INSERTION_ID)
                                    .setRequestId(REQUEST_ID))
                            .addImpression(Impression.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setInsertionId(INSERTION_ID)
                                    .setImpressionId(IMPRESSION_ID))
                            .addAction(Action.newBuilder()
                                    .setPlatformId(PLATFORM_ID)
                                    .setUserInfo(UserInfo.newBuilder().setLogUserId(CAMEL_CASED_LOG_USER_ID))
                                    .setTiming(createTiming(TIME_EPOCH_MILLIS))
                                    .setImpressionId(IMPRESSION_ID)
                                    .setActionId(ACTION_ID))
                            .build()));
  }
}
